### ISSUE TITLE
Realizar 5W2H

### ISSUE THREAD

**Issue by EliasOliver21** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_01#1]
Criação do 5W2H em equipe.

**Comment by pabloheika** [comment]
Etapa realizada durante a Designer Sprint no [Excel](https://unbbr-my.sharepoint.com/:x:/g/personal/180128817_aluno_unb_br/EUsBg96DxY9Otp92NKW3lwwBagYHiEBydH2glQB5c-nWew?e=cvNiaT)
![image](https://github.com/user-attachments/assets/bbe009b2-10aa-447d-8dfa-d6ebe9f3b4d2)
