### ISSUE TITLE
Realizar notação BPMN aplicada ao Scrum, XP e Kanban

### ISSUE THREAD

**Issue by claudiohsc** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_01#14]
### Summary

Realizar a modelagem das metodologias do Grupo 5 através da notação BPMN.

- [x] Scrum
  - [x] Sprint
  - [x] Sprint Planning
  - [x] Sprint Development
- [x] XP (Pair Programming)
- [x] Kanban

### Motivation

Tornar a visão do grupo mais ampla sobre todo o processo evolutivo da construção do software EvenTour.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by claudiohsc** [comment]
Eu e @EliasOliver21 começamos o esboço da notação voltado ao Scrum, especificamente na parte da Sprint e Sprint Planning.

**Comment by pabloheika** [comment]
Foi realizada uma reunião para o desenvolvimento do Sprint planning e review conforme a [gravação](https://youtu.be/Vbmy7QDjG6Y). 
Todos os participantes estão no video e no commit [93d5073](https://github.com/UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_01/commit/93d507341558575ce9bdc66069de148e76f82b91).
