### ISSUE TITLE
Protótipo de Alta Fidelidade

### ISSUE THREAD

**Issue by JoelSRangel** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_01#15]
### Summary

Criar um protótipo de alta fidelidade no Figma para o projeto EvenTour. O objetivo é fornecer uma visão realista e detalhada do design da interface, permitindo a visualização de elementos interativos e fluxos de navegação que simulem a experiência final do usuário.

### Motivation

O protótipo de alta fidelidade ajudará a equipe a validar as principais escolhas de design e funcionalidade antes do desenvolvimento, garantindo que todas as partes interessadas possam avaliar e aprovar o layout final. Esse protótipo também servirá como um recurso visual importante para identificar melhorias, testar interações e alinhar as expectativas da equipe sobre a experiência do usuário e o visual do produto.

### Alternatives

- Prototipagem de baixa fidelidade: Enquanto esboços ou wireframes são úteis nas fases iniciais, eles não transmitem a estética final e as microinterações que um protótipo de alta fidelidade oferece.
- Prototipagem diretamente no código: Construir um protótipo diretamente em HTML/CSS poderia ser uma alternativa, mas exige mais tempo e recursos de desenvolvimento.

### Additional Context

Este protótipo deve ser consistente com o branding visual definido para o projeto. Ele deve incluir todos os fluxos de navegação relevantes, animações de transição principais e simulações de interação (ex.: cliques, deslizes). Idealmente, a equipe deve basear o protótipo em elementos reutilizáveis para facilitar ajustes rápidos e futuras atualizações.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JoelSRangel** [comment]
O protótipo será feito em: 
https://www.figma.com/design/Sqv6j3v06RgzAIbtZvjCRR/EvenTour---Site?node-id=2-2&t=Ox0GpFXIXyxnBB0T-1

**Comment by pabloheika** [comment]
Histórico do Figma ate este momento:
![image](https://github.com/user-attachments/assets/5207f9f5-00db-498b-a905-32be02b96abe)
![image](https://github.com/user-attachments/assets/b70837d3-6d19-4f4e-bc9f-4a9f89247979)
![image](https://github.com/user-attachments/assets/50622f97-ed0e-4749-8512-955a7aab1b71)
![image](https://github.com/user-attachments/assets/47aef973-eccc-4467-8336-23a053842685)
![image](https://github.com/user-attachments/assets/84c4e244-63e6-48a9-9370-997fa2c5036f)
