### ISSUE TITLE
Documentar causa-efeito

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_01#24]
Documentar causa-efeito

**Comment by samuelalvess** [comment]
Finalizei a documentação do artefato generalista do Diagrama Causa-Efeito junto ao @gmeister18.

**Comment by pabloheika** [comment]
Causa-efeito realizado no teams com o auxilio do [Microsoft Whiteboard](https://unbbr-my.sharepoint.com/:wb:/g/personal/180128817_aluno_unb_br/Ebd3vhewh5lMjxbzp8AueyIBJjYpILd5buNst7GeI6LHuQ?e=PxX5Qf)
