### ISSUE TITLE
Protótipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by JoelSRangel** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_01#4]
### Summary

Realizar a confeccção do protótipo de baixa fidelidade visando as seguintes funcionalidades:
- login/cadastro de usuário (usar interface gráfica básica/padrão do Google - Material Design)
- primeira aba: informações sobre a cultura
- segunda aba: mostra os eventos perto da pessoa com base na localização
                              - filtros: escolher região
                              - visualizar evento, informações como data, cardápio, atrações
                              - favoritar evento (para receber lembretes)
                              - olhar comentários de pessoas que já foram
- terceira aba: administrar o evento
                            - criar evento
                            - mudar dados (data, preço etc)
- meu perfil
                            - ver favoritos
                            - ver meus eventos
                            - receber alertas
                            
E ficou definido a seguinte divisão:
- [x] Pablo e Cláudio: primeira aba 
- [x] Joel e Elias: segunda 
- [x] Samuel e Pedro Menezes: terceira aba
- [x] Lara e Pedro Paulo: meu perfil

### Motivation

A motivação para a criação de um protótipo de baixa fidelidade com essas funcionalidades é testar a usabilidade e organizar o fluxo de navegação, facilitando ajustes iniciais para garantir que a interface atenda às necessidades dos usuários e proporcione uma experiência intuitiva e funcional.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pabloheika** [comment]
Eu e o @claudiohsc concluímos as telas da primeira aba sobre as culturas dos festivais. 
https://unbbr-my.sharepoint.com/:f:/g/personal/180128817_aluno_unb_br/EhctuIbvGO9Ip7XdUGgwXIABYcP_A7vVfJpBNKmzefV4eQ?e=2QelKf

**Comment by Pedrin0030** [comment]
Eu e a @klmurussi finalizamos a parte do protótipo de baixa fidelidade da tela meu perfil. Segue abaixo os modelos:
[desktop](https://drive.google.com/drive/folders/1VdnFsp22b-hXVjHo1hRji_KIGdkkh8Ej?usp=sharing)
[mobile](https://share.balsamiq.com/c/bEMwi1E3r2HmFis9sVniPf.jpg)

**Comment by EliasOliver21** [comment]
Eu e o @JoelSRangel concluímos os frames em desktop e mobile da representação das telas de: comentários, eventos, avaliações e filtros. Abaixo o link com as imagens:
https://unbbr-my.sharepoint.com/:f:/g/personal/221007706_aluno_unb_br/ElmSjIdEPLBHqaUlId7RClYB1FK6HlnYLD8_CFt9QkHRlQ?e=5Qtqkj
