### ISSUE TITLE
Validação Protótipo de baixa fidelidade 

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_01#6]
### Summary

Realizar a validação do protótipo de baixa fidelidade com pelo menos três voluntários, apresentando o termo de consentimento e realizando gravação(vídeo) e o artefato de documentação do mesmo.

### Motivation

A validação do protótipo de baixo fidelidade vai garantir que a usar habilidade planejada, pelo grupo reflete a realidade comum de um usuário padrão. Como essa validação conseguimos identificar previamente problemas a serem resolvidos antes da implementação.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samuelalvess** [comment]
Realizada a validação do protótipo de baixa fidelidade com @gmeister18
