### ISSUE TITLE
Elicitaçao de requisitos e perfil de Usuário por meio de Questionário.

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_01#7]
### Summary

Elaboração de questionário web para ampla divulgação em rede, buscando resolver questões de perfil de usuário e elicitação de requisitos. Para isso o questionário deve apresentar o termo de consentimento, e em seguida fazer questões relacionadas ao perfil do usuário (não a identificação pessoal), e então fazer perguntas pertinentes a elicitação dos requisitos para o projeto.

### Motivation

Uma licitação de requisitos por meio de questionários conseguiremos abranger um público maior e ter uma maior fidelidade quanto aos dados obtidos, também poderemos conseguir um perfil mais preciso sobre os usuários.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by claudiohsc** [comment]
Utilizaremos como base a Bibliografia o Livro de IHC:
Barbosa, S. D. J.; Silva, B. S. da; Silveira, M. S.; Gasparini, I.; Darin, T.; Barbosa, G. D. J. (2021)
 Interação Humano-Computador e Experiência do usuário. Autopublicação. ISBN: 978-65-00-19677-1.
