### ISSUE TITLE
Design Sprint

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_01#8]
### Summary

Realizar o processo de sprint design inspirado no método do Google Venture passando pelos cinco passos e sendo eles.

Passo 1 entender: realização de um brainstorm para a elaboração de ideias, quanto ao quem são os usuários?, quais são suas necessidades?, qual contexto?, avaliação do concorrente e formular uma estratégia, resultando no artefato de mapa mental.

- [x] Brainstorm
- [x] Mapa mental

Passo 2 divergir: Imaginar, desenvolver muitas soluções e idealizar. Resultando nos artefatos 5W2H, rich picture e causa-efeito.

- [x] Debate de ideias
- [x] 5W2H
- [x] Rich picture
- [x] causa-efeito.

Passo 3 decidir: Escolher a melhor ideia, Decidindo qual foi o melhor rich picture e elaborar Storyboards.

- [x] Escolha do projeto 
- [x] Storyboards
- [x] Escolha do rich picture

Passa 4 protótipação: construir um protótipo de baixa fidelidade com foco na usar habilidade.

- [x] Protótipo de baixa fidelidade.

Passo 5 validação: validar o protótipo de baixa fidelidade com usuários reais fora do projeto, aprender a selecionar o que entra ou não no escopo do projeto, e realizar o levantamento de requisitos.

- [x] Validação do protótipo de baixa fidelidade.
- [x] levantamento de requisitos.

### Motivation

Com a realização do design sprint conseguimos sair da abstração, para algo mais concreto tendo uma visão mais direcionada do que será o projeto.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gmeister18** [comment]
criação do artefato junto ao @samuelalvess.
