### ISSUE TITLE
Elicitação de requisitos por entrevistas

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_01#9]
### Summary

Realização de pelo menos três entrevistas com pessoas que atendem o perfil de usuário para levantamento de requisitos. Deve ser apresentado o termo de consentimento e realizar a gravação da entrevista. A entrevista deve começar fazendo perguntas genéricas para entender o perfil do usuário, e então fazer perguntas relacionadas ao escopo do projeto para levantamento de requisitos.

### Motivation

Por meio de entrevistas teremos mais uma metodologia de elicitação, garantindo uma melhor diversidade de técnicas para minimizar falhas.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by klmurussi** [comment]
entrevista às 15h com Milena, da Atlética Pesadelo. Ela possui experiência organizando e divulgando eventos, como de halloween.

https://unbbr-my.sharepoint.com/:v:/g/personal/180042378_aluno_unb_br/EasPj2WkCmJMl9s034T3sJwBDqeGZ-xVMWTsfTDbGvj4DA?e=KdIlKf&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

**Comment by analufernanndess** [comment]
Entrevista com Maria Luiza. Ela procura eventos para poder ir.

https://unbbr-my.sharepoint.com/:v:/g/personal/221008688_aluno_unb_br/EX-csv6naGNMvaAB4tQVZJoB72FB-vg54-ezNK0IAUloKg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=ggwHWB

Entrevista com Pedro Arthur. Ele também procura eventos típicos para poder ir.
https://unbbr-my.sharepoint.com/:v:/g/personal/221008688_aluno_unb_br/EXxPsYLQfJpCoOlJUYA7INcBTAs7aBkybxQxLspBMg_pqw?e=vqhdcI&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D
